### PR TITLE
icc_examin + oyranos cleanup, fix SRC_URI and DEPEND

### PR DESCRIPTION
**Pull request by a17r**
Also, I'm thinking of pkgmoving to _icc-examin_ to match the project name on github - any opinions?

Plus: bug 467068 should be closed once and for all, and it does look like bug 536646 may head in the same direction.

### CODE REVIEW

**Comment by mgorny** [comment]
Next time, please try to open separate PR for each package unless they're very closely bound (i.e. you can't change one without changing the other).

**Comment by mgorny** [comment]
@xmw,  your packages involved, please take a look.

**Comment by a17r** [comment]
Yeah, in this case I put them in one PR because oyranos-0.9.4 can't be dropped before icc_examin-0.54

**Comment by xmw** [comment]
Please leave the drop decision to us.

**Comment by xmw** [comment]
```
+*oyranos-0.9.5-r1 (05 Aug 2015)
+
+  05 Aug 2015; Michael Weber <xmw@gentoo.org> +oyranos-0.9.5-r1.ebuild,
+  oyranos-0.9.5.ebuild, oyranos-9999.ebuild:
+  Revbump to implement changes of p/r 164 (thanks a17r).
+
```

**Comment by xmw** [comment]
```
+*icc_examin-9999 (05 Aug 2015)
+*icc_examin-0.55-r1 (05 Aug 2015)
+
+  05 Aug 2015; Michael Weber <xmw@gentoo.org> +icc_examin-0.55-r1.ebuild,
+  +icc_examin-9999.ebuild, metadata.xml:
+  Revbump to implement changes of p/r 164 (thanks a17r).
+
```

**Pull request closed without merging**
