### PR TITLE
=net-im/vacuum-9999: repository/homepage urls update

### PR DESCRIPTION
**Pull request by KetothXupack**
Nothing special. Small fix for project homepage and repo uri update.

### CODE REVIEW

**Comment by mgorny** [comment]
git-2 is no longer maintained. Please use git-r3.

**Comment by KetothXupack** [comment]
done :)

**Comment by mgorny** [comment]
```
+  26 May 2015; Michał Górny <mgorny@gentoo.org> vacuum-9999.ebuild:
+  Update remote repository VCS and URL for the live ebuild.
+  https://github.com/gentoo/gentoo-portage-rsync-mirror/pull/129 by
+  KetothXupack.
```

Since this is trivial, I have merged it directly. Thanks a lot :).

**Comment by KetothXupack** [comment]
no problems!

**Pull request closed without merging**
