### PR TITLE
Merge fbsd/amd64/{9.1,9.2}/clang profiles to arch/amd64-fbsd/clang

### PR DESCRIPTION
**Pull request by nigoro**
Content is the same. Details Gentoo bug 491654.
https://bugs.gentoo.org/show_bug.cgi?id=491654

### CODE REVIEW

**Comment by mgorny** [comment]
Please disregard travis' failure. I've just checked and that're the issues that were in the tree at the time, so no new issues.

**Comment by mgorny** [comment]
@aballier, @ryao: please review :).

**Comment by aballier** [comment]
yes it's good to go; @nigoro can be trusted for fbsd stuff I think: I've never understood why he didn't return as a gentoo dev :)

**Comment by aballier** [comment]
@nigoro: maybe it'd be worth to factorize further by creating a clang-system-compiler feature under profiles/features

**Comment by mgorny** [comment]
Improved my script and merged. Hopefully everything went right :).

**Pull request closed without merging**
