### PR TITLE
Version bump: www-servers/nginx-1.7.12

### PR DESCRIPTION
**Pull request by jbergstroem**
Updated http_headers_more module to 0.26.

### CODE REVIEW

**Comment by mgorny** [comment]
@dev-zero, you seem to be the primary maintainer here.

**Comment by jbergstroem** [comment]
@mgorny I regularly push this through proxy since @dev-zero is busy at times. @mrueg suggested me posting to here instead.

**Comment by mgorny** [comment]
Sure, just making him aware of this :). @ highlights is equivalent of CC-ing here :).

**Comment by jbergstroem** [comment]
I'm aware of that (hence the mrueg pull :))

**Comment by mgorny** [comment]
```
+*nginx-1.7.12 (16 Apr 2015)
+
+  16 Apr 2015; Michał Górny <mgorny@gentoo.org> +nginx-1.7.12.ebuild:
+  Version bump along with http_headers_more module update.
+  https://github.com/gentoo/gentoo-portage-rsync-mirror/pull/97 by jbergstroem.
```

**Pull request closed without merging**
