### PR TITLE
Next version Gentoo/FreeBSD 10.1

### PR DESCRIPTION
**Pull request by nigoro**
Hello.

FreeBSD 9.1 and 9.2 became EoL on December 31, 2014.
FreeBSD 8.2 is not supported from three years ago... ( EoL date, July 31, 2012 )

We need version that is supported by upstream to fix new security issues and errata.

Howto make Gentoo/FreeBSD 10.1 distfiles)

``` bash
mkdir /tmp/distfiles-10.1 && cd /tmp/distfiles-10.1
git clone git://git.overlays.gentoo.org/proj/gentoo-bsd.git
gentoo-bsd/scripts/extract-9.0.sh 10.1
ls -1 freebsd-*xz
put freebsd-*xz to dev.g.o:/space/distfiles-local
# cd /tmp && rm -rf /tmp/distfiles-10.1
```

Note,
I have not deleted old version of the ebuild at this time.
Required wiki update for upgrade info.

FYI,
ebuild of changes please see commit log.
http://cgit.gentooexperimental.org/proj/gentoo-bsd.git/

[Bug 529358] Next version Gentoo/FreeBSD 10.1
https://bugs.gentoo.org/show_bug.cgi?id=529358

[Bug 529292] [10.0] virtual/libiconv-0-r1: revision bump request
https://bugs.gentoo.org/show_bug.cgi?id=529292

[Bug 488214] Next version Gentoo/FreeBSD 10.0
https://bugs.gentoo.org/show_bug.cgi?id=488214

### CODE REVIEW

**Comment by mgorny** [comment]
I've committed profile changes and trying to commit the packages, I'm now getting fetch failure for `freebsd-lib-10.1.tar.xz`. Please fix this ASAP.

**Comment by nigoro** [comment]
You can get it by using a script. 
How to use the script, please see the first comment (Howto make Gentoo/FreeBSD 10.1 distfiles) of this request.

Howto make Manifest

``` bash
mv freebsd-* /usr/portage/distfiles
cd ~/gentoo-cvs/sys-freebsd
for pkg in boot0 freebsd*
do
    cd ${pkg}
    ebuild ${pkg} manifest
    cd ..
done
```

**Comment by mgorny** [comment]
dist-local is discouraged these days. I've placed the distfiles @ `http://dev.gentoo.org/~mgorny/dist/freebsd/${PV}/${P}.tar.xz`, please update the SRC_URIs accordingly.

**Comment by nigoro** [comment]
I've updated SRC_URI. ${RV} is defined by freebsd.eclass.

http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/eclass/freebsd.eclass?view=markup

**Comment by mgorny** [comment]
Merged. Thanks a lot, and sorry for the delay.

**Pull request closed without merging**
