### PR TITLE
[app-admin/elektra] Version bump

### PR DESCRIPTION
**Pull request by a17r**
Invert PLUGINS logic, improve ebuild
Fixes bugs 519492, 514402

TODO:
- Someone please test w/ augeas and qt5 (I can try the latter next week)
- Make bindings available (not aware of any demand right now)

### CODE REVIEW

**Comment by mgorny** [comment]
@xmw

**Comment by a17r** [comment]
0.8.12 release contains all the cmake fixes so patches could be dropped.

**Comment by xmw** [comment]
+*elektra-0.8.12 (05 Aug 2015)
+*elektra-9999 (05 Aug 2015)
+
+  05 Aug 2015; Michael Weber <xmw@gentoo.org> +elektra-0.8.12.ebuild,
+  +elektra-9999.ebuild, +files/elektra-0.8.11-conditional-glob-tests.patch,
+  elektra-0.8.7.ebuild, metadata.xml:
+  Version bump, add live ebuild, https://github.com/gentoo/gentoo-portage-rsync-
+  mirror/pull/165 (thanks a17r).
+

**Comment by xmw** [comment]
```
+*elektra-0.8.12 (05 Aug 2015)
+*elektra-9999 (05 Aug 2015)
+
+  05 Aug 2015; Michael Weber <xmw@gentoo.org> +elektra-0.8.12.ebuild,
+  +elektra-9999.ebuild, +files/elektra-0.8.11-conditional-glob-tests.patch,
+  elektra-0.8.7.ebuild, metadata.xml:
+  Version bump, add live ebuild, https://github.com/gentoo/gentoo-portage-rsync-
+  mirror/pull/165 (thanks a17r).
+
```

**Pull request closed without merging**
