### PR TITLE
net-libs/iojs-2.3.1: zlib fixes

### PR DESCRIPTION
**Pull request by jbergstroem**
..was missing because I assumed it was a required part of World.

Ref https://bugs.gentoo.org/show_bug.cgi?id=553212.

### CODE REVIEW

**Comment by jbergstroem** [comment]
Now also includes a fix for installing `USE=bundled-libs emerge iojs` which was the result of sloppy use of `sed`. It will still fail to install because of an npm issue..

**Comment by mgorny** [comment]
How about some := in deps, while already updating them? :)

**Comment by jbergstroem** [comment]
Fwiw, I still haven't had time to hunt down why npm cries. To be honest, I'm pretty keen on killing `bundled-libs` anyway.

@mgorny thoughts on dropping `bundled-libs` before merging everything back to nodejs? (months away)

Edit: I'll give it one more hour; might as well..

**Comment by mgorny** [comment]
Drop it!

**Comment by mgorny** [comment]
Could you rebase this, please?

**Comment by jbergstroem** [comment]
@mgorny we were removing `bundled-libs` in #166. Closing :)

Bonus points: if you could create a `-r1` with the changes left out in latest iojs that'd be great.

**Comment by mgorny** [comment]
I barely have time to review and merge stuff :). Please create PRs with any changes you want done :).

**Comment by jbergstroem** [comment]
@mgorny essentially everything in #166, as is (patrick just bumped).

**Pull request closed without merging**
