### PR TITLE
sys-auth/openpam: Version bump to fix a security issue, bug 512498

### PR DESCRIPTION
**Pull request by nigoro**
Details please see https://bugs.gentoo.org/show_bug.cgi?id=512498

### CODE REVIEW

**Comment by mgorny** [comment]
Shouldn't we remove all old versions as well?

**Comment by nigoro** [comment]
Yes, please remove all old version.

**Comment by mgorny** [comment]
Next time, please include that in the PR :). `git rm` gets converted into `cvs rm` automatically.

**Comment by mgorny** [comment]
```
+*openpam-20140912 (22 Feb 2015)
+
+  22 Feb 2015; Michał Górny <mgorny@gentoo.org> +openpam-20140912.ebuild,
+  -openpam-20071221.ebuild, -openpam-20111218.ebuild,
+  -openpam-20120526-r1.ebuild, -openpam-20120526.ebuild,
+  -openpam-20130907.ebuild:
+  Version bump for security bug #512498. Remove old. https://github.com/gentoo
+  /gentoo-portage-rsync-mirror/pull/35 by nigoro.
```

Thanks.

**Comment by nigoro** [comment]
Okay, thanks for info.
I do it from the next time ;-)

**Pull request closed without merging**
