### PR TITLE
x11-themes/clearlooks-phenix: Version bump.

### PR DESCRIPTION
**Pull request by gbraekmans**
Removed the slots from the previous builds. Don't see the use case here.
Solves bug #543508

Is maintainer-needed and I am willing to proxy-maintain.

### CODE REVIEW

**Comment by gbraekmans** [comment]
Sorry for the extra commit, but I can't seem to delete it in the pull request.

**Comment by mgorny** [comment]
You need to practice git a bit :).

Try:

```
git pull --rebase
```

Then it will likely stop at some conflict with the `update` commit.

```
git rebase --skip
```

And you should be fine. But make sure not to lose your original commit. Then:

```
git push -f
```

with appropriate remote & branch, and the PR should get updated.

**Comment by gbraekmans** [comment]
Indeed. Couldn't find a way to get the conflicts resolved.

**Comment by mgorny** [comment]
So are you trying to fix this or should we close it, and you open a new one?

**Comment by gbraekmans** [comment]
Close it, it's in the tree already. I was thinking you did that, but I guess not?

**Comment by mgorny** [comment]
Nope, sorry.

**Pull request closed without merging**
