### PR TITLE
app-backup/tsm: Fix bug #530900

### PR DESCRIPTION
**Pull request by marbre**
Fixes bug [#530900](https://bugs.gentoo.org/show_bug.cgi?id=530900).

### CODE REVIEW

**Comment by mgorny** [comment]
I see that this was merged as part of #190.

**Comment by marbre** [comment]
Well, the fix is included in/was merged into tsm-7.1.2.0, but the [ChangeLog](https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/app-backup/tsm/ChangeLog?view=markup) indicates that 7.1.0.0-r1 is still not fixed.

**Comment by mgorny** [comment]
Oh, ok.

**Comment by mgorny** [comment]
Good news, everyone! Gentoo now is in git and CVS lies dead. Bad news is that we don't have CVS to merge those pull requests into, and we need you to recreate the PRs on the officlal mirror @ https://github.com/gentoo/gentoo. Until we have official contribution guides, few quick notes:
1. No ChangeLogs in git.
2. You need to update Manifest this time, note that it's thin Manifest now.
3. Commit structure and commit messages do matter. take a look at https://wiki.gentoo.org/wiki/Gentoo_git_workflow.
4. Preferably sign your commits with your GPG key. Suggestions for your GPG key you can find in https://wiki.gentoo.org/wiki/GLEP:63.

Enjoy being few steps closer to a real Gentoo developer!

**Pull request closed without merging**
