### PR TITLE
net-libs/obby - depend on net/avahi[dbus] for libavahi-client (bug #473740), update header

### PR DESCRIPTION
**Pull request by mm1ke**
Pretty old bug [1] but still valid. (tested today)
Would be great if we could patch the ebuild in order to fix this bug.
I've also updated the header (year) in order to make repoman happy :)

[1] https://bugs.gentoo.org/show_bug.cgi?id=473740

### CODE REVIEW

**Comment by mgorny** [comment]
Ok, I can confrim that `avahi[-dbus]` doesn't install libavahi-client. Funny design.

**Comment by mgorny** [comment]
No need to update years btw, echangelog does that when we commit :).

**Comment by mgorny** [comment]
Merged now.

**Comment by mm1ke** [comment]
thx, good to know - won't update the year in the future :)

**Pull request closed without merging**
