### PR TITLE
Use pcheck instead of repoman

### PR DESCRIPTION
**Pull request by mgorny**
Unfinished and I'm going to sleep. I'll fix it tomorrow unless someone beats me to it.

@mrueg, @junghans.

### CODE REVIEW

**Comment by junghans** [comment]
```
The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).
```

**Comment by mgorny** [comment]
It's getting better and better now. Now I'm working on fixing the checks to be correct.

**Comment by mgorny** [comment]
We need to wait for @radhermit to fix pkgcore wrt implicit IUSE.

**Comment by mgorny** [comment]
I guess there's no point waiting more. Better have a 'mostly' working CI that will error out at few last packages than none at all.

@swegener, could you merge this, please?

**Pull request merged**
