### PR TITLE
Fix plasma5 vs. kde4 conflicts

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by mgorny** [comment]
Looks fine to me but let's wait for KDE team to review it.

**Comment by a17r** [comment]
The REQUIRED_USE in kde-meta might be debatable, setting the flag through plasma profile could suffice.

**Comment by johu** [comment]
:+1:  Looks good to me

**Comment by mgorny** [comment]
```
+  26 Jul 2015; Michał Górny <mgorny@gentoo.org>
+  targets/desktop/kde/package.use, targets/desktop/plasma/package.use:
+  Fix plasma5 vs kde4 conflicts.
+  https://github.com/gentoo/gentoo-portage-rsync-mirror/pull/183 by a17r.
```

(and the two ebuilds)

**Pull request closed without merging**
